DROP TABLE [dbo].[SavedFoods];
DROP TABLE [dbo].[UserIngredients];
DROP TABLE [dbo].[LabelledIngredients];
DROP TABLE [dbo].[FODMAPIngredients];
DROP TABLE [dbo].[AspNetUserRoles];
DROP TABLE [dbo].[AspNetUserClaims];
DROP TABLE [dbo].[AspNetUserLogins];
DROP TABLE [dbo].[AspNetUsers];
DROP TABLE [dbo].[AspNetRoles];