INSERT INTO [dbo].[FODMAPIngredients] (Name) VALUES
	('Agave Syrup'),
	('Amaranth Flour'),
	('Barley'),
	('Buttermilk'),
	('Einkorn'),
	('Emmer'),
	('Fruit Concentrate'),
	('Garlic'),
	('Glucose-fructose syrup'),
	('Watermelon'),
	('Tinned Fruit in Natural Juice'),
	('Honey'),
	('Fructose'),
	('High Fructose Corn Syrup'),
	('Fruit Juice'),
	('Milk'),
	('Ice Cream'),
	('Yogurt'),
	('Ricotta'),
	('Cottage Cheese'),
	('Asparagus'),
	('Beetroot'),
	('Broccoli'),
	('Cabbage'),
	('Fennel'),
	('Garlic Powder'),
	('Garlic Salt'),
	('Okra'),
	('Rye'),
	('Baked Beans'),
	('Rambutan'),
	('Longan'),
	('Cauliflower'),
	('Onion Salt'),
	('Onion Powder'),
	('Dried Fruit'),
	('Fruit Juice'),
	('Gram Flour'),
	('Inulin'),
	('Isoglucose'),
	('Isolated Fructose'),
	('Lentil Flour'),
	('Lupin'),
	('Sour Cream'),
	('Spelt'),
	('Fructans'),
	('Lactose'),
	('Apple Juice'),
	('Custard'),
	('Sweetened condensed milk'),
	('Falafel'),
	('Sausage'),
	('Salami')
GO

INSERT INTO [dbo].[FODMAPIngredients] (Name, Aliases) VALUES
	('Mushroom', 'Mushrooms'),
	('Cashews', 'Cashew'),
	('Pistacios', 'Pistacio'),
	('Figs', 'Fig'),
	('Blackberries', 'Blackberry'),
	('Spring Onions', 'Spring Onion'),
	('Split Peas', 'Split Pea'),
	('Green Peas', 'Green Pea'),
	('Snow Pea', 'Snow Peas'),
	('Milk Curds', 'Milk Curd'),
	('Chickory Root', 'Chickory Extract'),
	('Custard Apple', 'Custard Apples'),
	('White Peaches', 'White Peach'),
	('Chickpeas', 'Chickpea'),
	('Lychee', 'Lychees'),
	('Nectarine', 'Nectarines'),
	('Peach', 'Peaches'),
	('Plum', 'Plums'),
	('Prune', 'Prunes'),
	('Avocado', 'Avocados'),
	('Persimmon', 'Persimmon'),
	('Apricot', 'Apricots'),
	('Cherries', 'Cherry'),
	('Lentils', 'Lentil'),
	('Red Kidney Beans', 'Red Kidney Bean'),
	('Nashi Pear', 'Nashi Pears'),
	('Leeks', 'Leek'),
	('Onions', 'Onion'),
	('Peas', 'Pea'),
	('Shallots', 'Shallot'),
	('Brussels sprout', 'Brussels Sprouts'),
	('Clingstone Peaches', 'Clingstone Peach'),
	('Mango', 'Mangoes'),
	('Artichokes', 'Artichoke'),
	('Sugar Snap Peas', 'Sugar Snap Pea'),
	('Pear', 'Pears'),
	('Apple', 'Apples'),
	('Khorasan Flour', 'Kamut'),
	('Chickpea Flour', 'Besan'),
	('Sorbitol','E420'),
	('Mannitol', 'E410'),
	('Xylitol','E967'),
	('Maltitol','E965'),
	('Isomalt','E953'),
	('Erythritol', 'E968'),
	('Fructooligosaccharides', 'FOS'),
	('Wheat', 'Gluten')
GO