INSERT INTO [dbo].[FODMAPIngredients] (Name) VALUES
	('Agave Syrup'),
	('Amaranth Flour'),
	('Barley'),
	('Buttermilk'),
	('Einkorn'),
	('Emmer'),
	('Fruit Concentrate'),
	('Garlic'),
	('Glucose-fructose syrup'),
	('Tinned Fruit in Natural Juice'),
	('Honey'),
	('Fructose'),
	('High Fructose Corn Syrup'),
	('Fruit Juice'),
	('Milk'),
	('Ice Cream'),
	('Yogurt'),
	('Ricotta'),
	('Cottage Cheese'),
	('Asparagus'),
	('Beetroot'),
	('Broccoli'),
	('Cabbage'),
	('Fennel'),
	('Garlic Powder'),
	('Garlic Salt'),
	('Okra'),
	('Rye'),
	('Baked Beans'),
	('Rambutan'),
	('Longan'),
	('Cauliflower'),
	('Onion Salt'),
	('Onion Powder'),
	('Dried Fruit'),
	('Fruit Juice'),
	('Gram Flour'),
	('Inulin'),
	('Isoglucose'),
	('Isolated Fructose'),
	('Lentil Flour'),
	('Lupin'),
	('Sour Cream'),
	('Spelt'),
	('Fructans'),
	('Lactose'),
	('Apple Juice'),
	('Custard'),
	('Sweetened condensed milk'),
	('Falafel'),
	('Sausage'),
	('Salami')
GO

INSERT INTO [dbo].[FODMAPIngredients] (Name, Aliases) VALUES
	('Mushroom', 'Mushrooms'),
	('Watermelon', 'Watermellon'),
	('Cashews', 'Cashew'),
	('Pistacios', 'Pistacio'),
	('Figs', 'Fig'),
	('Blackberries', 'Blackberry'),
	('Spring Onions', 'Spring Onion'),
	('Split Peas', 'Split Pea'),
	('Green Peas', 'Green Pea'),
	('Snow Pea', 'Snow Peas'),
	('Milk Curds', 'Milk Curd'),
	('Chickory Root', 'Chickory Extract'),
	('Custard Apple', 'Custard Apples'),
	('White Peaches', 'White Peach'),
	('Chickpeas', 'Chickpea'),
	('Lychee', 'Lychees'),
	('Nectarine', 'Nectarines'),
	('Peach', 'Peaches'),
	('Plum', 'Plums'),
	('Prune', 'Prunes'),
	('Avocado', 'Avocados'),
	('Persimmon', 'Persimmon'),
	('Apricot', 'Apricots'),
	('Cherries', 'Cherry'),
	('Lentils', 'Lentil'),
	('Red Kidney Beans', 'Red Kidney Bean'),
	('Nashi Pear', 'Nashi Pears'),
	('Leeks', 'Leek'),
	('Onions', 'Onion'),
	('Peas', 'Pea'),
	('Shallots', 'Shallot'),
	('Brussels sprout', 'Brussels Sprouts'),
	('Clingstone Peaches', 'Clingstone Peach'),
	('Mango', 'Mangoes'),
	('Artichokes', 'Artichoke'),
	('Sugar Snap Peas', 'Sugar Snap Pea'),
	('Pear', 'Pears'),
	('Apple', 'Apples'),
	('Khorasan Flour', 'Kamut'),
	('Chickpea Flour', 'Besan'),
	('Sorbitol','E420'),
	('Mannitol', 'E410'),
	('Xylitol','E967'),
	('Maltitol','E965'),
	('Isomalt','E953'),
	('Erythritol', 'E968'),
	('Fructooligosaccharides', 'FOS'),
	('Wheat', 'Gluten')
GO

INSERT INTO [dbo].[Quotes] (Body, Author) VALUES
    ('I swear I''ll branch. Promise.', 'Tanner'),
    ('All Scrum, no master.', 'Tanner'),
    ('That''s like a whole scrum effort point right there.', 'Jensen'),
    ('I can give you the "let''s normalize this database" look.', 'Jensen'),
    ('Make it more vogue.', 'Cassidy'),
    ('That''s the best flex I''ve heard all day.', 'Tanner'),
    ('"Cute and nonaggressive" that describes me pretty well.', 'Jensen'),
    ('We don''t even have a steak yet!', 'Tanner'),
    ('Is pathos just like being a dick?', 'Gabriel'),
    ('That is a powerful vibrate!', 'Jensen'),
    ('I''m combining some of the things, but not all of them.', 'Cassidy'),
    ('Ow I got something in my eye, wow this room is really dusty or something they should fix that cuz I might look like I''m crying but I''m totally not.', 'Jensen'),
	('If I''m drinking, I''m drinking. If I''m coding, I''m coding.', 'Tanner'),
	('Don''t clutch your rosary at me!', 'Tanner'),
	('I just timeboxed myself, bro.', 'Tanner'),
	('I live for cardinal sin.', 'Cassidy'),
	('Anything is a board if you''re brave enough.', 'Tanner'),
	('New year,  new pancreas.', 'Tanner'),
	('That''s a heckin'' Irish last name.', 'Jensen'),
	('Your peanut butter is pretty flexible.', 'Jensen'),
	('Notice the chili...', 'Tanner'),
	('But how do you keep your goldfish clean?', 'Jensen'),
	('Oh no, I changed Testy''s password.', 'Jensen'),
	('All manual testing shall be done with chili.', 'Jensen'),
	('This quantum robot hamster is sneckin''.', 'Jensen'),
	('The real associates degree is the friends you made along the way.', 'Tanner'),
	('It''s not going right now, but it goes.', 'Gabriel'),
	('Hmmmmmmgwahhh.', 'Jensen'),
	('I can have all the things that I want!', 'Cassidy'),
	('Ease of use equals ease of bowel movements.', 'Jensen'),
	('Yeah, you want to have a "fresh" object to play with.', 'Gabriel'),
	('Fear the might of Beansi!', 'Tanner'),
	('Did someone fix the... uh... Nope, its still anal', 'Gabriel'),
	('I thought you were talking in flatus.', 'Tanner'),
	('Class inheritance is like onions', 'Tanner')
GO